---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-and-linter
spec:
  params:
  - description: SourcecoderepositoryURL
    name: source-repo
    type: string
  workspaces:
    - name: pipeline-shared-data
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: lint
      runAfter:
        - clone-repository
      taskRef:
        name: markdown-lint
      workspaces:
        - name: shared-workspace
          workspace: pipeline-shared-data
      params:
        - name: args
          value: ["."]
