
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-lint-
spec:
  params:
    - name: source-repo
      value: https://github.com/upslopeio/lint-markdown-files
  pipelineRef:
    name: git-and-linter
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
              
              
